apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: cozy-fluxcd
spec:
  interval: 60m0s
  retryInterval: 6m0s
  timeout: 4m0s
  path: ./examples/metrics-server
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cozy-fluxcd
    namespace: cozy-fluxcd
