apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: admin-cozy-fleet
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-repo-admin-creds
      namespace: crossplane-system
      key: credentials
