apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: vcluster
  name: vcluster
  namespace: vcluster-vcluster-cluster
spec:
  controlPlaneEndpoint:
    host: vcluster.vcluster-vcluster-cluster.svc
    port: 443
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.22.3
    values: |
      controlPlane:
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          host: vcluster-cluster.turkey.local
          spec:
            tls:
            - hosts:
              - vcluster-cluster.turkey.local
              - vcluster.vcluster-vcluster-cluster.svc
              secretName: vcluster-cluster-tls
        distro:
          k3s:
            enabled: true
            extraArgs:
            - --kube-apiserver-arg=oidc-issuer-url=https://dex.harvey.moomboo.space
            - --kube-apiserver-arg=oidc-client-id=wg-kubelogin
            - --kube-apiserver-arg=oidc-groups-claim=groups
            - --disable=rolebindings,runtimes
            - --disable-helm-controller
            image:
              tag: v1.30.8-k3s1
        proxy:
          extraSANs:
          - vcluster-cluster.turkey.local
          - vcluster.vcluster-vcluster-cluster.svc
