apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: sshkeys.platform.example.org
spec:
  group: platform.example.org
  names:
    kind: SSHKey
    plural: sshkeys
  claimNames:
    kind: SSHKeyClaim
    plural: sshkeyclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
            status:
              type: object
      defaultCompositionRef:
        name: ssh-key-composition
