apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ssh-key-composition
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: ssh-key-job
      base:
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: ssh-key-generator
        spec:
          template:
            spec:
              containers:
                - name: keygen
                  image: alpine
                  command: ["sh", "-c"]
                  args:
                    - |
                      ssh-keygen -t rsa -b 2048 -f /tmp/id_rsa -N "" &&
                      kubectl create secret generic ssh-key-secret \
                      --from-file=id_rsa=/tmp/id_rsa \
                      --from-file=id_rsa.pub=/tmp/id_rsa.pub \
                      --dry-run=client -o yaml | kubectl apply -f -
                  volumeMounts:
                    - mountPath: /tmp
                      name: temp
              restartPolicy: OnFailure
              volumes:
                - name: temp
                  emptyDir: {}
