apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ssh-key-composition
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: SSHKey
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: ssh-key-job
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: ssh-key-generator
          namespace: crossplane-system
        spec:
          forProvider:
            manifest:
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: ssh-key-generator
                namespace: crossplane-system
              spec:
                template:
                  spec:
                    containers:
                      - name: keygen
                        image: bitnami/ssh-keygen:latest
                        command: ["sh", "-c"]
                        args:
                          - |
                            ssh-keygen -t rsa -b 2048 -f /tmp/id_rsa -N "" &&
                            kubectl create secret generic ssh-key-secret \
                            --from-file=id_rsa=/tmp/id_rsa \
                            --from-file=id_rsa.pub=/tmp/id_rsa.pub \
                            --dry-run=client -o yaml | kubectl apply -f -
                        volumeMounts:
                          - mountPath: /tmp
                            name: temp
                    restartPolicy: OnFailure
                    volumes:
                      - name: temp
                        emptyDir: {}
          providerConfigRef:
            name: local-k8s # Reference to the Kubernetes ProviderConfig
