apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: vcluster-mop
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: vcluster-mop-cluster
      name: mop-kubeconfig
      key: value
