apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 5m
  timeout: 1m
  targetNamespace: goldilocks
  storageNamespace: goldilocks
  chart:
    spec:
      chart: dex
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: goldilocks
      interval: 5m
  values:
