apiVersion: v1
kind: Service
metadata:
  name: planet
  namespace: socryx-topled
spec:
  ports:
  - name: urbit-http
    port: 8080
  - name: urbit-https
    port: 8443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: planet
  namespace: socryx-topled
subsets:
- addresses:
  - ip: 10.17.12.102
  ports:
  - port: 8080
    name: urbit-http
  - port: 8443
    name: urbit-https
