apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vcluster-with-access
spec:
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: access
          base:
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            spec:
              managementPolicies: ["Observe", "Create", "Update", "Delete"]
              forProvider:
                manifest:
                  apiVersion: rbac.authorization.k8s.io/v1
                  kind: ClusterRoleBinding
                  metadata:
                    name: kingdon-ci:cozy-vcluster-sre
                  roleRef:
                    apiGroup: rbac.authorization.k8s.io
                    kind: ClusterRole
                    name: cluster-admin
                  subjects:
                  - apiGroup: rbac.authorization.k8s.io
                    kind: Group
                    name: kingdon-ci:cozy-vcluster-sre
              providerConfigRef:
                name: vcluster-moo
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.group"
              toFieldPath: "spec.forProvider.manifest.metadata.name"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.group"
              toFieldPath: "spec.forProvider.manifest.subjects[0].name"
            - type: CombineFromComposite
              combine:
                variables:
                  - fromFieldPath: "spec.vClusterName"
                strategy: string
                string:
                  fmt: "vcluster-%s"
              toFieldPath: "spec.providerConfigRef.name"
  compositeTypeRef:
    apiVersion: access.urmanac.com/v1alpha1
    kind: Access
