apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-job-manager
  namespace: crossplane-system
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crossplane-job-manager-binding
  namespace: crossplane-system
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crossplane-job-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-ssh-key-creator-binding
  namespace: crossplane-system
subjects:
  - kind: ServiceAccount
    name: ssh-key-job-service-account
    namespace: crossplane-system
roleRef:
  kind: Role
  name: job-ssh-key-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: crossplane-system
  name: job-ssh-key-creator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssh-key-job-service-account
  namespace: crossplane-system
