apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-ssh-key-creator-binding
  namespace: cozy-fluxcd
subjects:
  - kind: ServiceAccount
    name: ssh-key-job-service-account
    namespace: cozy-fluxcd
roleRef:
  kind: Role
  name: job-ssh-key-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cozy-fluxcd
  name: job-ssh-key-creator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssh-key-job-service-account
  namespace: cozy-fluxcd
